name: Run Discord Bot

# ===========================
# トリガー
# ===========================
on:
  schedule:
    - cron: "0 */6 * * *"  # 6時間ごと（UTC基準）
  workflow_dispatch:        # 手動実行も可能

# ===========================
# 重複防止
# ===========================
concurrency:
  group: discord-bot
  cancel-in-progress: true  # 新しいジョブが来たら前のジョブを必ず停止

# ===========================
# ジョブ定義
# ===========================
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      # 2. Pythonセットアップ
      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. 依存ライブラリインストール
      - name: 依存ライブラリをインストール
        run: |
          python -m pip install --upgrade pip
          pip install nextcord asyncio-throttle requests

      # 4. Botを起動（6時間で自動終了）
      - name: Discord Bot起動
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          echo "✅ Bot starting..."
          timeout 6h python main.py
