name: Run Discord Bot

on:
  schedule:
    - cron: "*/6 * * * *"  # 6分ごとに自動実行（UTC）
  workflow_dispatch:        # 手動実行も可能

concurrency:
  group: discord-bot
  cancel-in-progress: true  # 前のジョブが残っていれば停止

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 依存ライブラリインストール
        run: |
          python -m pip install --upgrade pip
          pip install nextcord asyncio-throttle requests

      - name: Discord Bot起動
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          echo "✅ Bot starting..."
          python main.py  # timeout は不要
